version: "3.9"

services:
    
    php:
        container_name: php
        image: advent1:${version:-latest}
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80"
            - 9000:9000


    